modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/dima-dencep/rsgauges/issues"
license="MIT"

[[mods]]
modId="rsgauges"
version="${version}"
displayName="Gauges and Switches"
description="Adds redstone metering gauges, levers, buttons, pressure plates, and all sorts of other sensors and detector switches to the game."
authors="wilechaote, dima_dencep"
displayURL="https://github.com/dima-dencep/rsgauges"
logoFile="logo.png"

[[dependencies.rsgauges]]
  modId="forge"
  mandatory=true
  versionRange="[43,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.rsgauges]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.20,]"
  ordering="NONE"
  side="BOTH"
